### ISSUE TITLE
Missing exportAs inside brnTabs

### ISSUE THREAD

**Issue by benjaminforras** [goetzrobin/spartan#105]
### Please provide the environment you discovered this bug in.

Missing exportAs inside brnTabs

### Which area/package is the issue in?

tabs

### Description

The issue occurs when  I try to create a custom component and trying to access brnTabs value.

![image](https://github.com/goetzrobin/spartan/assets/10364896/cd16dfec-601b-4a22-be56-113023702688)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
I'll add this ASAP!

**Comment by goetzrobin** [comment]
Issue was addressed as part of releases: cli 0.0.1-alpha.334 & ui 0.0.1-alpha.321
