### ISSUE TITLE
RFC: Carousel

### ISSUE THREAD

**Issue by goetzrobin** [goetzrobin/spartan#117]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

TBD

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
We will wrap around the official Angular wrapper: https://github.com/davidjerleke/embla-carousel/pull/627

**Comment by goetzrobin** [comment]
This is now possible with the following official Angular wrapper: https://github.com/donaldxdonald/embla-carousel-angular

**Comment by theo-matzavinos** [comment]
I took a stab at this since it seemed pretty straightforward. The API I went with looks like this:

```
   <hlm-carousel orientation="horizontal" [plugins]="emblaPlugins">
      <hlm-carousel-content>
        <hlm-carousel-item>...</hlm-carousel-item>
        <hlm-carousel-item>...</hlm-carousel-item>
      </hlm-carousel-content>
      <button hlm-carousel-previous></button>
      <button hlm-carousel-next></button>
    </hlm-carousel>
```

Let me know if this is the direction you had in mind and if I should open a PR.

**Comment by goetzrobin** [comment]
looks awesome! One thing I'd might change is the directives for the buttons to become: `hlmCarouselPrevious` and `hlmCarouselNext`. Looking forward to your PR @theo-matzavinos
