### ISSUE TITLE
Lucide icons

### ISSUE THREAD

**Issue by r3ps4J** [goetzrobin/spartan#122]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

Hi! First of all, thanks for the great work. It's good to finally see one of these ui libraries make its way to Angular.

I noticed that you're using radix icons for the components while adhering to the default style of shadcn/ui, but shadcn uses lucide icons for the default style and radix icons for the New York style.

So, I was wondering if it wouldn't be better to provide the components with lucide icons by default. That would make sure the style is consistent between the two libraries, as well as the Figma file.

I saw that lucide icons are also supported by ng-icons, which is currently used for the radix icons. So I'm guessing that swapping one out for the other won't cause any issues. (I don't have any experience with ng-icons though so forgive me if I'm wrong on that)

---

Side question that may need another issue: are there any plans on supporting the New York style as well?

### Describe any alternatives/workarounds you're currently using

Swapping them out manually in our own projects is probably a good workaround (haven't gotten a chance to test it yet tho), but I was thinking more about the consistency of the provided components between this and shadcn/ui.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
Absolutely! We talked about this internally and I think this would be a great PR if you want to take this on 🙏🚀

**Comment by r3ps4J** [comment]
Great!

**Comment by goetzrobin** [comment]
@r3ps4J do you still want to work on this?

**Comment by goetzrobin** [comment]
@r3ps4J do you still want to work on this?

**Comment by goetzrobin** [comment]
@r3ps4J do you still want to work on this?

**Comment by goetzrobin** [comment]
@r3ps4J do you still want to work on this?

**Comment by r3ps4J** [comment]
Yeah definitely! Sorry for the delay, I have some deadlines for my studies that I need to hand in so I didn't want to start yet to avoid having to merge other changes when I can work on it. You can expect the PR sometime next week, hope it's not a pressing issue
