### ISSUE TITLE
support tailwind merge 2.2

### ISSUE THREAD

**Issue by waltherjochen** [goetzrobin/spartan#143]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

Hello everyone,

Please support Tailwind Merge 2.2

I saw that the PR [(125)](https://github.com/goetzrobin/spartan/pull/125) was merged, but it still does not work.

Thank you!

```
npm i @spartan-ng/ui-core
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: app@0.0.0
npm ERR! Found: tailwind-merge@2.2.1
npm ERR! node_modules/tailwind-merge
npm ERR!   dev tailwind-merge@"^2.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwind-merge@"^1.14.0" from @spartan-ng/ui-core@0.0.1-alpha.335
npm ERR! node_modules/@spartan-ng/ui-core
npm ERR!   @spartan-ng/ui-core@"0.0.1-alpha.335" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@waltherjochen thanks for reporting this! This is an dependency issue for the ui-core package! I'll take a look and make sure to fix it as part of the next release!

**Comment by goetzrobin** [comment]
@waltherjochen this should be fixed with the newest alpha!
