### ISSUE TITLE
Use of host metadata 

### ISSUE THREAD

**Issue by corentinclichy** [goetzrobin/spartan#146]
### Please provide the environment you discovered this bug in.

NX@latest
angular@latest

### Which area/package is the issue in?

typography

### Description

Hi, 

When I install primitives for typography, for example, I get the host declared as metadata. 

### Please provide the exception or error you saw

```true
I get an Eslint error: 

**Use @HostBinding or @HostListener rather than the `host` metadata property (https://angular.io/styleguide#style-06-03)**
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
The Angular team is actually now recommending to use `host` over HostBinding and HostListener.
Here is the documentation that states this: https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators
We are also adhering to this new standard and use host. You can disable the eslint rule for the spartan libraries that are created by the CLI by adding this to your .eslintrc.json:
```json
{
	"overrides": [{
		"files": ["*.ts"],
		"rules": {
			"@angular-eslint/no-host-metadata-property": 0,
			...
			}
		}]
}
```

**Comment by corentinclichy** [comment]
Ok thanks a lot for the support
