### ISSUE TITLE
not able to select primitives 

### ISSUE THREAD

**Issue by akshata456** [goetzrobin/spartan#150]
### Please provide the environment you discovered this bug in.

[angular-storybook-demo.zip](https://github.com/goetzrobin/spartan/files/14235928/angular-storybook-demo.zip)
"@angular/cli": "^17.1.3",
 "storybook": ["^7.6.13",]()
"tailwindcss": "^3.4.1",
 "@spartan-ng/cli": "^0.0.1-alpha.336",
 "@spartan-ng/ui-core": "^0.0.1-alpha.335",

### Which area/package is the issue in?

Don't know / other

### Description

trying setup in angular cli 
<img width="941" alt="Screenshot 2024-02-12 at 1 12 00 PM" src="https://github.com/goetzrobin/spartan/assets/34393874/e95220e3-ce32-4e03-978a-9147cde20bed">

Adding primitives
ng g @spartan-ng/cli:ui
after running this cmd it show like 

### Please provide the exception or error you saw

```true
let me know what is breaking in this step .thanks in advance
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@akshata456 thanks for bringing this up! How are you selecting the primitives? It is done with Space instead of Enter. I have made that mistake before, does this help at all?

**Comment by akshata456** [comment]
@goetzrobin by using space it's working now , thanks .
