### ISSUE TITLE
Select adheres to New York style

### ISSUE THREAD

**Issue by r3ps4J** [goetzrobin/spartan#166]
### Which scope/s are relevant/related to the feature request?

select

### Information

Shadcn/ui has a "Default" and "New York" style. Right now the project only copies the default style, but the "Select" component copies over the New York style (check icon being on the right side, caret sort instead of chevron down as icon, no inset for items, probably more). It should be corrected so it doesn't look weird / out of place in combination with the other components.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@thatsamsonkid is this still the case? If so, can you adjust the styles to be the regular version? We might want to look into adding a New York style version of hlm! Could be cool. Not 100% on how we'd go about it, but could probably spin something up with the current nx-to-hlm generator

**Comment by r3ps4J** [comment]
Shadcn seems to use a registry with the same component for each style, not sure how he does it for the hlm stuff though

**Comment by thatsamsonkid** [comment]
You know I thought I had switched it back at some point before we merged it in but I must have missed it somehow. I'll update it to the default!
