### ISSUE TITLE
Configure prettier as a pre-commit hook & GitHub Action

### ISSUE THREAD

**Issue by ajitzero** [goetzrobin/spartan#17]
While working on #16 I noticed that 86 files have changed after running Prettier, most of them untouched by me. Looks like prettier was not run explicitly in some commits.

I recommend 2 things:
1. Set up husky to trigger `npm run prettify` as a pre-commit hook locally. - This is straightforward.
1. Set up a GitHub Action to format the project after merging any MR to the main branch. This is useful for people directly editing just the docs via the GitHub website. - I can't find a reliable reference right now,  but I have seen this being done in other projects with an extra commit by github-actions-bot to include Prettier changes.

**Comment by ajitzero** [comment]
@goetzrobin I can look into setting this up over this weekend if this sounds reasonable. Please let me know your thoughts on this.

**Comment by goetzrobin** [comment]
Thanks for all your efforts and catching that! This should be run as part of the lintstaged hook as defined the .lintstagedrc file.

Seems like some slipped through the cracks... we can run prettier on all and see if the issue pops up again.

**Comment by ajitzero** [comment]
Should I run prettier in my existing PR then? Even if it modifies files outside my scope of changes? The CI flagged my PR correctly to not have formatting done.

**Comment by ajitzero** [comment]
I think we can close this one since newer PRs will always go through commit lint & prettier in the CI process. The commit hook also seems to be in place so the issues we saw earlier were probably before prettier was added to the CI action.
