### ISSUE TITLE
Bug: Getting HTMLElement is not defined error

### ISSUE THREAD

**Issue by deepakrudrapaul** [goetzrobin/spartan#19]
### Please provide the environment you discovered this bug in.

Ubuntu 22.04.3 LTS
Node Version - v18.14.2

### Which area/package is the issue in?

Don't know / other

### Description

Getting the below error: 

Step 1 - run yarn dev
Step 2- Goto http://127.0.0.1:4200/

![Screenshot from 2023-08-13 13-10-11](https://github.com/goetzrobin/spartan/assets/25549935/c54f096d-9ad4-430b-8289-280eb82b5ca9)

![image](https://github.com/goetzrobin/spartan/assets/25549935/8580fee2-f60c-458a-b757-87f764dd6c01)

### Please provide the exception or error you saw

```true
An error occured while server rendering /index.html:

	HTMLElement is not defined
ReferenceError: HTMLElement is not defined
    at <static_initializer> (/home/deepak/Desktop/PW/OpenSource/spartan/projects/ngx-scrollbar/src/lib/utils/ng-attr.directive.ts:201:169)
    at /home/deepak/Desktop/PW/OpenSource/spartan/projects/ngx-scrollbar/src/lib/utils/ng-attr.directive.ts:160:4
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
I am running into this too. This is only during development and the build still works as expected. 

To get the dev server up and running:
- Find the scroll bar module 
- Uncomment the NgScrollbarModule
- Uncomment everything but the ng-content in the template

I think this is an issue with the Analog Vite dev server. I reached out to Brandon for help on this

**Comment by deepakrudrapaul** [comment]
Thanks for the solution

**Comment by goetzrobin** [comment]
@deepakrudrapaul this should be working in the master branch now. I'll also update the README.md to be a little more helpful
