### ISSUE TITLE
table: page size select options of data table preview isn't visible in darkmode

### ISSUE THREAD

**Issue by danilolmc** [goetzrobin/spartan#192]
### Please provide the environment you discovered this bug in.

At table component preview page

### Which area/package is the issue in?

Docs

### Description

In dark mode, when attempting to select a page size for the data table, the selection options remain hidden due to the options having both a white background and white font color. The option value only becomes visible upon hovering.

![Captura de Tela (44)](https://github.com/goetzrobin/spartan/assets/31545128/8ec24012-e225-4720-acff-3a6b75671a1b)

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
Good catch! We should probably replace this with our new custom select component, which @thatsamsonkid finished the other day! Do you want to take a crack at it or should I take a look? @danilolmc

**Comment by danilolmc** [comment]
Thanks @goetzrobin!

Replacing it with the select component it's a good one. I can take a crack at it!

**Comment by danilolmc** [comment]
Fixed by #221
