### ISSUE TITLE
 Property 'class' does not exist on type 'BrnColumnDefComponent'

### ISSUE THREAD

**Issue by andrejsipka** [goetzrobin/spartan#196]
### Please provide the environment you discovered this bug in.

`export class HlmThComponent {
	private readonly _columnDef? = inject(BrnColumnDefComponent, { optional: true });
	protected readonly truncate = input(false, { transform: booleanAttribute });

	public readonly userClass = input<ClassValue>('', { alias: 'class' });
	protected readonly _computedClass = computed(() =>
		hlm(
			'flex flex-none h-12 px-4 text-sm items-center font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0',
			this._columnDef?.class(),     **<======== Doesn't exist**
			this.userClass(),
		),
	);
}`

### Which area/package is the issue in?

table

### Description

After changing access modifier in the **table** component from `private` to `public` for useClass inputSignal, compiler encountered an error in both HlmThComponent and HlmTdComponent. 

### Please provide the exception or error you saw

```true
TS2339: Property 'class' does not exist on type 'BrnColumnDefComponent'. [plugin angular-compiler]
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by elite-benni** [comment]
This should be fixed with #164.
https://github.com/goetzrobin/spartan/pull/164

**Comment by marcus-sa** [comment]
@elite-benni when will you cut a new working release?

**Comment by elite-benni** [comment]
the next release is planned for today, hopefully @goetzrobin finds the time to release it.

**Comment by goetzrobin** [comment]
@marcus-sa @andrejsipka this should be addressed now. Please let me know if this issue is resolved after you upgrade
