### ISSUE TITLE
Command line ng g @spartan-ng/cli:ui with all option does not import all directive component

### ISSUE THREAD

**Issue by KhoaLee** [goetzrobin/spartan#208]
### Please provide the environment you discovered this bug in.

Angular project without using Nx, using only ng cli 

### Which area/package is the issue in?

Don't know / other

### Description

First provide the following cli in the image without specific suffix directive. Then select the option "all", as I understand this option will import all directive to the libs/ui folder location
<img width="870" alt="image" src="https://github.com/goetzrobin/spartan/assets/33981342/b1650f7c-4fb2-4a12-ab18-d5df3766f816">

However, it returns "No items were selected". This could be due to 2 possible cases. 

1. First is the suffix directive option was not provide hence the cli think that no items were selected even we selected from the list of option. 
2. Second is the "all" option was not available at the moment for importing all directive at once

<img width="1327" alt="image" src="https://github.com/goetzrobin/spartan/assets/33981342/d24b2528-083b-47c4-bbdb-6944cef48379">

I could be wrong on the use case of cli. Hope someone can clarify the usage of "all" option.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
I released a new version of the CLI today. Please let me know if this fixes this issue

**Comment by KhoaLee** [comment]
Thanks for you quick response. It is working now after selecting "all" option with the spacebar. @goetzrobin
