### ISSUE TITLE
Spartan-ng/cli@0.0.1-alpha.339 fails on ng g with Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by redzimskidev** [goetzrobin/spartan#210]
### Please provide the environment you discovered this bug in.

New Angular app without Nx

### Which area/package is the issue in?

accordion

### Description

Steps to reproduce:
1) ng g @angular/cli@latest -g
2) ng new
3) install tailwind
4) follow spartan manual for installation
5) on ng g @spartan-ng/cli:ui fails with Cannot convert undefined or null to object no matter what options I chose
Installing @0.0.1-alpha.337 fixed the issue.

### Please provide the exception or error you saw

```true
Cannot convert undefined or null to object
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by i-am-the-slime** [comment]
Same problem here, do you know of a workaround? This is for everything not just accordion for me.

**Comment by redzimskidev** [comment]
Yeah, on version version 0.0.1-alpha.337 it works fine.

**Comment by i-am-the-slime** [comment]
Perfect, thanks I'll pin that for now!

**Comment by goetzrobin** [comment]
Just released a fix for this with version 340! Please upgrade :)
