### ISSUE TITLE
not able to generate code (either using angular api or nx) for sonner

### ISSUE THREAD

**Issue by dez1729** [goetzrobin/spartan#230]
### Please provide the environment you discovered this bug in.

spartan-ng/cli 0.0.1-alpha.343

### Which area/package is the issue in?

sonner

### Description

When trying to run the angular cli or nx command to generate code for sonner, I'm getting the following error message:

````
(intermediate value).generator is not a function
````
![image](https://github.com/goetzrobin/spartan/assets/20635596/db9477fd-8aeb-4b9f-86f1-9818a784f713)

### Please provide the exception or error you saw

```true
(intermediate value).generator is not a function
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
I'll take a look tomorrow

**Comment by dez1729** [comment]
thanks saw your push it works now...sort of. the generated file is misnamed to `hlm-toaster-component.ts` instead of `hlm-toaster.component.ts`

**Comment by goetzrobin** [comment]
@dez1729 just released another version. does it work now?

**Comment by goetzrobin** [comment]
Fixed in the newest alpha!
