### ISSUE TITLE
Docs mention @ngneat/cmdk instead of @ngxpert/cmdk

### ISSUE THREAD

**Issue by kkamman** [goetzrobin/spartan#243]
### Please provide the environment you discovered this bug in.

- https://www.spartan.ng/components/command
- https://www.spartan.ng/documentation/about

### Which area/package is the issue in?

Docs

### Description

The following pages mention @ngneat/cmdk instead of @ngxpert/cmdk, and link to https://ngneat.github.io/cmdk/ instead of https://ngxpert.github.io/cmdk/:
- https://www.spartan.ng/components/command
- https://www.spartan.ng/documentation/about

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by elite-benni** [comment]
Hey @kkamman  thanks for pointing that out, feel free to open an PR. 
I have assigned you to this issue!
