### ISSUE TITLE
Bug: .env isn't added to the .gitignore

### ISSUE THREAD

**Issue by evanfuture** [goetzrobin/spartan#28]
### Please provide the environment you discovered this bug in.

Locally, after installing via nx-create-workspace

### Which area/package is the issue in?

Don't know / other

### Description

Following the Installation docs, there's a point where it's suggested to create a .env file in the project root.  But the gitignore doesn't reference that file, so newer folks might accidentally commit it.

### Other information

Maybe this belongs in the analogjs/platform repo instead.  Let me know if that's the case.  An alternative fix would be to add a comment in the docs reminding them not to commit sensitive files to their repo...

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
I think adding a note to the docs should be good for this!

Thanks for looking into this!

**Comment by santoshyadavdev** [comment]
@goetzrobin I added a note in the doc

**Comment by goetzrobin** [comment]
@santoshyadavdev thank you! Can you also add an alert with the same content to this page of the spartan.ng website: https://github.com/goetzrobin/spartan/blob/afb596ca0afd2868156c2f966e43391271469a06/apps/app/src/app/pages/(stack)/stack/installation.page.ts#L354

**Comment by santoshyadavdev** [comment]
I can see the warning exist on doc website? do you want to me to use that in docs here.

**Comment by goetzrobin** [comment]
You are absolutely right @santoshyadavdev! Thank you!
