### ISSUE TITLE
unable to install nx-workspace with presets

### ISSUE THREAD

**Issue by hafnerpw** [goetzrobin/spartan#288]
### Please provide the environment you discovered this bug in.

windows 11 
nodejs v20.13.0
nx-create-workspace v19.0.1 (latest)

### Which area/package is the issue in?

Docs

### Description

After running `npx create-nx-workspace@latest --preset=@analogjs/platform` and accepting the interactive cli questions as its written in the [docs ](npx create-nx-workspace@latest --preset=@analogjs/platform) I repeatedly run into an issue at npm install. 
running the terminal with admin rights doesn't make a diffrence.

![image](https://github.com/goetzrobin/spartan/assets/60545335/28690e0b-f3f4-474d-9a78-67f878a03d8f)

### Please provide the exception or error you saw

```true
NX   Command failed: npm install
 NX   Failed to apply preset: @analogjs/platform
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
I haven't tried out version 19 of Nx. We might have to make some adjustments for the latest changes. If you use the last version of 18 instead of @latest does it work?

**Comment by goetzrobin** [comment]
@hafnerpw please let me know if this is still an issue. I'll close this. If the issue persists please open a ticket in the analogjs repository and I'll check it out
