### ISSUE TITLE
Module Not recognize

### ISSUE THREAD

**Issue by Gomes2710** [goetzrobin/spartan#290]
When i trie import HlmInputDirective, is not recognize module.
I use jhipster
Does anyone know how to solve it?

![image](https://github.com/goetzrobin/spartan/assets/132093101/fcbb3975-1a25-4434-a01b-0e238f5b281a)

![image](https://github.com/goetzrobin/spartan/assets/132093101/d431dc83-3d90-4e3d-9b48-dcc6e5710776)

![image](https://github.com/goetzrobin/spartan/assets/132093101/019b4799-fba8-419d-abdc-996ca208b7f1)

![image](https://github.com/goetzrobin/spartan/assets/132093101/f9f92075-596a-4485-801b-cf2aff193859)

**Comment by goetzrobin** [comment]
That seems like a tspath issue. Is the beginning of the paths normal on Windows? I'm a Mac user 🙈

**Comment by Gomes2710** [comment]
I managed to solve it, thank you anyway
