### ISSUE TITLE
Brn and Hlm Error Directive for Form Fields

### ISSUE THREAD

**Issue by thatsamsonkid** [goetzrobin/spartan#294]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

Error messages for form controls currently need to be handled by user instead of having a directive similar to mat-error to handle showing and hiding the error message to the user and maintaining the style consistent with Shadcn

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by cjosue15** [comment]
Hi, this is my first time trying to contribute to open source, I think I have a solution to implement the same angular material functionality, but with shadcn style, so I would like to submit my PR.


https://github.com/goetzrobin/spartan/assets/51803643/2d6f2af6-ef04-4ae1-a02b-479a59f925b0
