### ISSUE TITLE
Accessing brain state inside wrapper directives/components

### ISSUE THREAD

**Issue by peterhodges** [goetzrobin/spartan#31]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

We maintain our own component library and love the concept of brain!

Ideally, we'll use brain directives/components to implement some of our components, while keeping brain encapsulated behind our component's API.

As an example, we've created a `MenuItemCheckbox` component that adds the `BrnMenuItemCheckboxDirective` as a hostDirective.

This works great, brain is handling the logic and exposing this via element states and classes so we can provide our own markup and style this appropriately.

However, we already have our own set of UI components (e.g. a checkbox) that we'd like to use inside of a `MenuItemCheckbox` component.

I notice in the Helm version of MenuItemCheckbox, you're hiding the checkbox with `opacity:0` and showing it based on the `checked` class added by brain.

Instead, I'd like to be able to access the "checked" state from `BrnMenuItemCheckboxDirective` and pass that through to my child component.

I notice you're passing around state (dialogs) using signals in other places. Maybe there's a good reason not to do it elsewhere?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
I use the class in the hlm because I want to keep the two decoupled, funny enough the idea is that you can use either with your own versions of brain/helm.

There's nothing I see that would prevent us from exposing the checked property directly. I just didn't want the hlm component to have to inject the brain component.

I can expose the checked and disabled properties for the checkbox and radio components. Would that be good enough?

**Comment by peterhodges** [comment]
Yeah that would be great.

I still see it as decoupled. Brain is handling the logic and keeping track of state, and just exposing that state to any wrappers so that they can provide their own markup (or custom components) and CSS.

E.g. I already have a checkbox that handles showing/hiding the right icon, animations etc. I want to be able to use that, but pass the "checked" state from brain to my custom component.

**Comment by peterhodges** [comment]
Awesome, thank you.

I'm building out a menu at the moment and had to revert to depending on Cdk directly, instead of brain, so I'll give it ago once the state is exposed.

I'll also try wrapping some other components from brain to see what other issues I run into.

Awesome library by the way. Good riddance to opinionated libraries like Material. There's so much unmaintainable spaghetti code around because people can't easily wrap their UI libraries behind their own abstractions. The angular community has needed something like this for years! Hopefully we can get Angular to play ball :D

**Comment by goetzrobin** [comment]
Yeah hopefully this concept of un-styled brain only components that take care of all the a11y for you, but are flexible enough to let them style however you need is catches on.

That way there is a single "brain" everyone can work together to make as good as possible and then on top of that give it their own styles.

Would be cool!

**Comment by goetzrobin** [comment]
Closed this for now and we can continue the discussion in the other issue
