### ISSUE TITLE
Not installing in angular 17

### ISSUE THREAD

**Issue by huzaifah-here** [goetzrobin/spartan#318]
### Please provide the environment you discovered this bug in.

Angular 17.3.0

### Which area/package is the issue in?

accordion

### Description

![image](https://github.com/goetzrobin/spartan/assets/66216337/3aab0a9a-2294-439d-956f-58463f3a4bd1)

I'm trying to install spartan ui in angular 17 and it giving me error. I know if i update angular cdk to 18 it will work but my requirement is to work in angular 17. I also tried, 
`npm i @spartan-ng/ui-core@17.3.0` 
but it doesnt have this version. 

I read docs but didnt find anything related to angular 17! 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Hey @huzaifah-here unfortunately we require Angular 18 as a minimum version for now.
