### ISSUE TITLE
Bartender not working

### ISSUE THREAD

**Issue by Pouchy20** [goetzrobin/spartan#341]
### Please provide the environment you discovered this bug in.

I have just finished all of my updates and logged into wow for the first time in a couple of months.  I have an issue with my spartan UI, that none of my bars are visible, Even when I try and move a spell to the bar. The outline for the UI is visible but no bar. I have reinstalled both addons and still no joy.  

### Which area/package is the issue in?

Don't know / other

### Description

I have just finished all of my updates and logged into wow for the first time in a couple of months.  I have an issue with my spartan UI, that none of my bars are visible, Even when I try and move a spell to the bar. The outline for the UI is visible but no bar. I have reinstalled both addons and still no joy.  

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by ajitzero** [comment]
Spartan is not SpartanUI 😅

Please report your issue(s) at https://github.com/Wutname1/SpartanUI/issues

**Comment by thatsamsonkid** [comment]
@Pouchy20 - closing as I think you meant this for a different repo as mentioned by @ajitzero
