### ISSUE TITLE
Memorize libs directory

### ISSUE THREAD

**Issue by tvollstaedt** [goetzrobin/spartan#355]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

Probably not very important issue, but I'm using a custom target path for installing components and need to type it every time I run the CLI generator. I know that there is the `--directory` parameter for the CLI, but I love how I can easily install components by c&p'ing from your website, so it would be really helpful if the CLI could just remember the first path I entered.

### Describe any alternatives/workarounds you're currently using

Enter the target directory everytime.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by goetzrobin** [comment]
We could introduce a similar `components.json` to keep track of this: https://ui.shadcn.com/docs/components-json
Thoughts?

**Comment by tvollstaedt** [comment]
> We could introduce a similar `components.json` to keep track of this: https://ui.shadcn.com/docs/components-json Thoughts?

Good idea, I was intentionally thinking about `package.json`, as it‘s what Angular and other CLI‘s use. But if you prefer to be closer to shadcdn, it could be a good option, especially when we intend to support the other options in future as well.
