### ISSUE TITLE
RFC: Ripple on Buttons

### ISSUE THREAD

**Issue by XanderDeLaet** [goetzrobin/spartan#356]
### Which scope/s are relevant/related to the feature request?

button

### Information

I feel like the button component can use a ripple effect to make it extra modern. This could be a ripple toggle, color white for dark mode and black for light mode

### Describe any alternatives/workarounds you're currently using

/

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by ajitzero** [comment]
This repo is pretty much aligned with shadcn/ui, so for something like a ripple effect, you're free to add it in your local version.

There's this: https://material.angular.io/components/ripple/examples#ripple-overview

And you can add this as a host directive to your button component.

**Comment by goetzrobin** [comment]
@ajitzero agree with this. unfortunately this is out of scope for us, but the good thing about owning the components is that you can extend them as you please!
