### ISSUE TITLE
Public alias of form-field-helm seems wrong

### ISSUE THREAD

**Issue by angelnikolov** [goetzrobin/spartan#358]
### Please provide the environment you discovered this bug in.

Angular 18, Nx 19

### Which area/package is the issue in?

Don't know / other

### Description

[form-field](https://github.com/goetzrobin/spartan/blob/30bf1fa0159b9534823db66cdc65a756b38089cc/libs/cli/src/generators/ui/libs/ui-form-field-helm/generator.ts#L10)
`publicName` is `ui-formfield-helm` (missing dash). 
Executing `npx nx g @spartan-ng/cli:ui form-field` generates a `tsconfig` path alias of `@spartan-ng/ui-formfield-helm`, which contradicts the documentation of the `form-field` package [here](https://www.spartan.ng/components/form-field) resulting in a compilation error of a wrong import.
```ts

import { HlmFormFieldModule } from '@spartan-ng/ui-form-field-helm';
import { HlmInputDirective } from '@spartan-ng/ui-input-helm';

```

### Please provide the exception or error you saw

```true
✘ [ERROR] TS2307: Cannot find module '@spartan-ng/ui-form-field-helm' or its corresponding type declarations. [plugin angular-compiler]

    libs/product-card/src/lib/product-card/product-card.component.ts:4:35:
      4 │ import { HlmFormFieldModule } from '@spartan-ng/ui-form-field-helm';
        ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by ajitzero** [comment]
Related #351
