### ISSUE TITLE
Tabs page doesn't work

### ISSUE THREAD

**Issue by artaommahe** [goetzrobin/spartan#363]
### Please provide the environment you discovered this bug in.

https://www.spartan.ng/components/tabs

### Which area/package is the issue in?

tabs

### Description

- open https://www.spartan.ng/components/tabs
- the page is empty
- there is an error in the console `Error: JIT compiler unavailable`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by marcjulian** [comment]
This should be fixed when #353 is merged.

**Comment by marcjulian** [comment]
Tabs page works again.
