### ISSUE TITLE
Missing modules in hlm-form-field and hlm-input

### ISSUE THREAD

**Issue by aghwotu** [goetzrobin/spartan#365]
### Please provide the environment you discovered this bug in.

```
    "@angular/cli": "^18.2.2",
    "@angular/compiler-cli": "^18.2.0",
    "@spartan-ng/cli": "^0.0.1-alpha.361",
```

### Which area/package is the issue in?

input

### Description

There are errors generated in two files: 

1. `hlm-input.directive.ts` 
```
import { BrnFormFieldControl } from '@spartan-ng/ui-form-field-brain';
import { ErrorStateMatcher, ErrorStateTracker } from '@spartan-ng/ui-forms-brain';
```

```
Cannot find module '@spartan-ng/ui-form-field-brain' or its corresponding type declarations
Cannot find module '@spartan-ng/ui-forms-brain' or its corresponding type declarations
```

2. `hlm-form-field.component.ts`
```
import { BrnFormFieldControl } from '@spartan-ng/ui-form-field-brain';
import { HlmErrorDirective } from './hlm-error.directive';
```

```
Cannot find module '@spartan-ng/ui-form-field-brain' or its corresponding type declarations
```

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/66ed2d00-fcc8-499b-89db-5fa84b49b6d3">

### Please provide the exception or error you saw

```true
✘ [ERROR] TS2307: Cannot find module '@spartan-ng/ui-form-field-brain' or its corresponding type declarations. [plugin angular-compiler]

    components/ui-input-helm/src/lib/hlm-input.directive.ts:4:36:
      4 │ import { BrnFormFieldControl } from '@spartan-ng/ui-form-field-brain';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module '@spartan-ng/ui-forms-brain' or its corresponding type declarations. [plugin angular-compiler]

    components/ui-input-helm/src/lib/hlm-input.directive.ts:5:53:
      5 │ ...tateMatcher, ErrorStateTracker } from '@spartan-ng/ui-forms-brain';
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Other information

Tailwind config
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("@spartan-ng/ui-core/hlm-tailwind-preset")],
  content: ["./src/**/*.{html,ts}", "./components/**/*.{html,ts}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by lreiner** [comment]
Is there a temporary fix for this? Even though the bugfix got merged I still get the same result using `npx nx g @spartan-ng/cli:ui formfield`

**Comment by goetzrobin** [comment]
I released the new cli which should fix this! Let me know if you get it to work now

**Comment by ajitzero** [comment]
Hi, @goetzrobin, I'm facing a similar issue with installing input & label. Where can I see the latest releases on GitHub? I'm on `0.0.1-alpha.362`

**Comment by goetzrobin** [comment]
That is the newest. Are you still getting the exact same error? I'll take a look

**Comment by ajitzero** [comment]
I'm facing an issue during installation itself:

![image](https://github.com/user-attachments/assets/c912bf99-72b2-4abd-806a-5490f59f1a59)

3 different error logs:
- "deps is not iterable" for formfield.
- "Cannot read properties of undefined (reading 'internalName')" for input.
- Label clsx version: I've just submitted a PR: https://github.com/goetzrobin/spartan/pull/373

**Comment by ajitzero** [comment]
Also, maybe unrelated, @spartan-ng/ui-core is on [`0.0.1-alpha.354`](https://www.npmjs.com/package/@spartan-ng/ui-core?activeTab=versions) - Should that be bumped to 362 as well?

**Comment by goetzrobin** [comment]
@ajitzero just pushed a new version. if you wanna try it. i am testing it now, too

**Comment by ajitzero** [comment]
It works now! (but) I'm seeing two versions of form field:

![image](https://github.com/user-attachments/assets/21d8e0ef-11c3-4a9f-b4de-4b38f97af021)

**Comment by goetzrobin** [comment]
i just pushed the final version (hopefully)

cli 0.0.1-alpha.364 & ui 0.0.1-alpha.355

you should be able to remove the ui-form-field-brain and dependency issues should be resolved

**Comment by goetzrobin** [comment]
@ajitzero let me know if everything looks good from your side now

**Comment by ajitzero** [comment]
All good! Thanks for helping out so quickly!

![image](https://github.com/user-attachments/assets/40c84fe1-ca4f-4703-917b-50e8699bf83d)

For some reason, the CLI generator had added these to the main package.json in the dependencies section, which I removed manually. I'll try this out in a different repo to check if that happens again or if I mistyped something.

**Comment by ajitzero** [comment]
@goetzrobin I just tried again after deleting node modules, and the original issue is happening again :(

![image](https://github.com/user-attachments/assets/992f0326-19c1-4b74-918c-57a4d2af6f0e)

`'@spartan-ng/ui-forms-brain'` clearly doesn't exist, so should this just be `'@spartan-ng/ui-core'`? Manually changing it doesn't work.

It's almost 3 am here, so I'll check again tomorrow. Good night!

**Comment by goetzrobin** [comment]
Hey there! The cli should install it the ui-forms-brain for you 🤔 I'll check it out tomorrow also

**Comment by marcjulian** [comment]
I think `@spartan-ng/ui-formfield-brain` is not yet published to npm, the package name was changed in the last commit [chore: release cli 0.0.1-alpha.364 & ui 0.0.1-alpha.355](https://github.com/goetzrobin/spartan/commit/6df5d65a13531d54c3a3b2051a0260108caf7689)

**Comment by ajitzero** [comment]
@marcjulian It's available on npm:
- https://www.npmjs.com/package/@spartan-ng/cli?activeTab=versions
- https://www.npmjs.com/package/@spartan-ng/ui-core?activeTab=versions

**Comment by marcjulian** [comment]
I was trying to install `@spartan-ng/ui-formfield-brain`. Now i can find it on npm too https://www.npmjs.com/package/@spartan-ng/ui-formfield-brain

**Comment by marcjulian** [comment]
There is a peer dependency issue with select pointing to `@spartan-ng/ui-form-field-brain@0.0.1-alpha.355` which only exists as `@spartan-ng/ui-formfield-brain@0.0.1-alpha.355`. Fixed with #374

**Comment by jhonna7an** [comment]
Hi, I'm afraid I'm having a problem with renaming the @spartan-ng/ui-form-field-brain package, because now I'm having a problem trying to install the @spartan-ng/ui-select-brain component. Is there any way to solve it? Thank you.

![Captura de pantalla 2024-09-22 130636](https://github.com/user-attachments/assets/876f6d56-778f-476a-a357-a74a6ba830a1)

**Comment by goetzrobin** [comment]
@jhonna7an I released a new version of the CLI and UI. make sure to remove the `@spartan-ng/ui-form-field-brain` from your package.json and the issues should be resolved. you might also need to wipe your node_modules if the issues persists. Let me know how it goes

**Comment by marcjulian** [comment]
@michahell `@spartan-ng/brain/form-field` has been removed and replaced by the [Field](https://github.com/spartan-ng/spartan/pull/1053) component in the version `@spartan-ng/brain@0.0.1-alpha.658`.  

The field package exports now

```ts
import { BrnFieldControl, provideBrnLabelable } from '@spartan-ng/brain/field';
```

Field handles now linking error/description and label to the form field and error styles for invalid and touched controls.
More details about this can be found here

- Validation and Errors - https://spartan.ng/components/field#validation-and-errors
- a11y - https://spartan.ng/components/field#accessibility
- Reactive forms examples - https://spartan.ng/forms/reactive-forms
