### ISSUE TITLE
Menubar component angular cli command wrong in docs

### ISSUE THREAD

**Issue by Adityacodesinpython** [goetzrobin/spartan#375]
### Please provide the environment you discovered this bug in.

I discovered it while importing the menubar component in the cli

### Which area/package is the issue in?

menubar

### Description

the angular cli command for menubar is given as `ng g @spartan-ng/cli:ui menubar` which doesn't work. 

the cli doesn't even respond as "wrong command" which makes it more difficult to correct.

### Please provide the exception or error you saw

```true
It shows "nothing to be done" when executing the command given in menubar docs.
```

### Other information

what worked for me was executing `ng g @spartan-ng/cli:ui menu`

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Thank you! I just updated the docs. should be fixed in a few minutes
