### ISSUE TITLE
Adding primitives : Cannot read properties of null (reading 'generators')

### ISSUE THREAD

**Issue by bpoulaindev** [goetzrobin/spartan#40]
### Please provide the environment you discovered this bug in.

Blank new project using Spartan UI and tailwind

### Which area/package is the issue in?

Don't know / other

### Description

Getting an error while adding primitives, whether installing "all" or just a single one.
Blank new project using bun, but same error with npm (even after running npm i for uninstalled dev dependencies)
Both following commands lead to the same error :
--> npx nx g @spartan-ng/nx:ui --verbose
--> npx nx g @spartan-ng/nx:ui card  

### Please provide the exception or error you saw

<img width="1379" alt="image" src="https://github.com/goetzrobin/spartan/assets/64689165/4af895a9-3b87-4060-9088-1bca77e5a1d3">

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Can you share what versions are used in the package.json? Seems like the issue stems from the @nx/angular package... I tried recreating with @spartan-ng/nx 0.0.1-alpha.315 and it worked (for now)

**Comment by goetzrobin** [comment]
I will close this for now. Let's open another issue for a CLI that does not depend on Nx!
