### ISSUE TITLE
RFC: Tooltip

### ISSUE THREAD

**Issue by mihajm** [goetzrobin/spartan#5]
# brn

---

## API (proposed)

I'd go with a material like approach, since global options in angular can be provided through DI & so a root component as seen in Radix/Shadcn is not required.

```html
<button (click)="doesStuff()" brnTooltip="Additional information" #tt="brnTooltip" brnTooltipPosition="before" ...>Click</button>

<button (click)="tt.show()">Show tooltip</button>
```

### Proposed types

```typescript
import { BooleanInput } from "@angular/cdk/coercion";

// before and after consider the direction of the text.
type TooltipPosition = "above" | "below" | "left" | "right" | "before" | "after";

type TooltipDisplayStrategy = "always" | "onHover" | "onFocus";

type TooltipDefaultOptions = {
  position: TooltipPosition; // default: 'below'
  positionAtOrigin: BooleanInput; // default: false
  showDelay: number; // default: 0
  hideDelay: number; // default: 0
  tooltipClass: string; // default: ''
  displayStrategy: TooltipDisplayStrategy; // default: 'always'
};

// directive exportAs reference
interface Tooltip {
  show(delayMilis?: number): void;
  hide(delayMilis?: number): void;
  toggle(delayMilis?: number): void;
}
```

Global options, can be overridden by overriding providers or by directive inputs

| Input                      | Type                   | Default  | Description                                                                   | Global Property  |
| -------------------------- | ---------------------- | -------- | ----------------------------------------------------------------------------- | ---------------- |
| brnTooltip                 | string                 | -        | The text to display in the tooltip                                            | -                |
| brnTooltipPosition         | TooltipPosition        | 'below'  | The position of the tooltip relative to the origin                            | position         |
| brnTooltipPositionAtOrigin | boolean                | false    | Whether the tooltip should be positioned at the origin or at the mouse cursor | positionAtOrigin |
| brnTooltipShowDelay        | number                 | 0        | The delay in miliseconds before the tooltip is shown                          | showDelay        |
| brnTooltipHideDelay        | number                 | 0        | The delay in miliseconds before the tooltip is hidden                         | hideDelay        |
| brnTooltipClass            | string                 | ''       | The class to apply to the tooltip                                             | tooltipClass     |
| brnTooltipDisplayStrategy  | TooltipDisplayStrategy | 'always' | The strategy to use for displaying the tooltip                                | displayStrategy  |

# hlm

---

Not sure what hlm would do here, as it's a purely logical component. If you have any style/variant ideas, I'm all ears. :) We could however just re-export every brn-only component as a hlm component for the sake of api consistency for hlm users.

# Aria

---

## Roles, States & Properties

- The tooltip itself should have `role="tooltip"` and `aria-hidden="true"` by default.
- the element the tooltip is applied to should have `aria-describedby` set to the tooltip's id.
  - `aria-describedby` should be appended if it already exists, since it allows for multiple element id's to be specified. (Ex. a badge and a tooltip on a notifications icon-button)
  - Technically a tooltip can be used as a label, this should then replace the `aria-describedby` with `aria-labelledby` and the tooltip should have `role="label"` instead of `role="tooltip"`. This is however not recommended & doesn't seem to be covered by radix/shadcn or angular material.
- The tooltip should always disapear on `esc` keypress.
- The tooltip should appear on `focus` and `hover` events to cover keyboard & mouse users.
  - When the tooltip is triggered by `hover` it should be dismissed on `mouseleave` or `esc` keypress.
  - When the tooltip is triggered by `focus` it should be dismissed on `blur` or `esc` keypress.
    - The tooltip can be annoying to keyboard users on `focus`, so an additional keypress is sometimes used to show the tooltip (Ex. `f2` when focused). We can make this optional by adding a `autoShowOnFocus` boolean option or a `requireKeyOnFocus` string option, which would show the tooltip on focus immediately if undefined.

## Source

[https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/)
[https://github.com/w3c/aria-practices/issues/128](https://github.com/w3c/aria-practices/issues/128)
[https://inclusive-components.design/tooltips-toggletips/](https://inclusive-components.design/tooltips-toggletips/)

# Radix

---

## API

```typescript
import React from "react";
import * as Tooltip from "@radix-ui/react-tooltip";
import { PlusIcon } from "@radix-ui/react-icons";
import "./styles.css";

const TooltipDemo = () => {
  return (
    <Tooltip.Provider>
      <Tooltip.Root>
        <Tooltip.Trigger asChild>
          <button className="IconButton">
            <PlusIcon />
          </button>
        </Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content className="TooltipContent" sideOffset={5}>
            Add to library
            <Tooltip.Arrow className="TooltipArrow" />
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip.Root>
    </Tooltip.Provider>
  );
};

export default TooltipDemo;
```

## Source

[https://www.radix-ui.com/docs/primitives/components/tooltip](https://www.radix-ui.com/docs/primitives/components/tooltip)

# shadcn

---

## API

```typescript
import { Plus } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

export function TooltipDemo() {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline" className="w-10 rounded-full p-0">
            <Plus className="h-4 w-4" />
            <span className="sr-only">Add</span>
          </Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>Add to library</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
```

## Source

[https://ui.shadcn.com/docs/components/tooltip](https://ui.shadcn.com/docs/components/tooltip)

**Comment by mihajm** [comment]
Another potential idea I'm currently implementing in our companies app is a global disable for tooltips, since power-users might find them annoying. We could make this a bit easier to do by adding a boolean prop to the options

**Comment by goetzrobin** [comment]
```ts
    <Tooltip.Provider>
      <Tooltip.Root>
        <Tooltip.Trigger asChild>
          <button className="IconButton">
            <PlusIcon />
          </button>
        </Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content className="TooltipContent" sideOffset={5}>
            Add to library
            <Tooltip.Arrow className="TooltipArrow" />
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip.Root>
    </Tooltip.Provider>
    ```
    When I compare radix and the proposed API theres a few questions:
    - I am fine with the material like approach. Again, having a root would simple be a way to hide the manual wiring up and add classes to the "overlay"/"dialog" background from material
    - I am missing the tooltip arrow part for the brn component. I think it is necessary, because it will enable us to style the arrow any way we want
    - We might need a brnToolTipTrigger directive since we allow a display strategy that reacts to hover, focus, and click. This is actually a huge pain to implement consistently across browsers. React aria has some great interactions that take care of that: https://react-spectrum.adobe.com/react-aria/useFocus.html I think a good enough start is just to use the Angular events though
    - I like the idea of disabling the tooltip. I wonder if that would be part of the trigger or the tooltip itself?

**Comment by mihajm** [comment]
Ah might be a bit of a misunderstanding, while the directives interface can be accessed through its export, the directive itself is all you need to create a tooltip

```html
<PlusIcon brnTooltip="tooltip content" />
```
Is all that would be required. The element itself then becomes the trigger/provider etc. So 0 wiring necessary. The portal with the provided content can then be added to the dom by the directive.

Forgot about the arrow :) tho I wouldn't require it so maybe a boolean input with a default of true, unless you see any other options that could be applied?

Yeah hopefuly focusmonitor can solve some of that pain :) Tho I dont think there's a way around it since it needs to support both keyboard, touch & mouse users. The rest is more a matter of disabling/enabling those event handlers. We can maybe internally separate all that into its own directive which is then simply composed in the root directive.

**Comment by goetzrobin** [comment]
First iteration of this is published. Closing this issue. We can create new issues for all future Bugs/Enhancements
