### ISSUE TITLE
Refactor Hostbinding to host property in the @Component decorator

### ISSUE THREAD

**Issue by elite-benni** [goetzrobin/spartan#55]
As stated in the angular.dev docs:

Always prefer using the host property over [@HostBinding](https://angular.dev/api/core/HostBinding) and [@HostListener](https://angular.dev/api/core/HostListener). These decorators exist exclusively for backwards compatibility.

Im gonna tackle this.

**Comment by goetzrobin** [comment]
Awesome! I like this, especially since we seem to run into some CD issues with the HostBinding and HostListener approach!

**Comment by elite-benni** [comment]
Started with the accordion and already had to do the same thing 4 times.
As noted in discord i thiught of something like a mutationObserver to automatically react on input changes, but i am afraid that this is notna good solution. 

My problem with this change is, that i wanted to find a common solution, because when signal based inputs arrive we will surely have to change this again. ;)

**Comment by goetzrobin** [comment]
Yes this is interesting, because I agree there will probably be another round of adjusting this to signal based inputs. I did see a good tweet about this. 

Maybe this is a signal input ready enough way of doing this:
https://x.com/tomastrajan/status/1725173414862672214?s=20

**Comment by elite-benni** [comment]
Thanks for this tip. 
I have changed all the Hostbindings. 
I guess the change will not be too hard, as i grouped the _userCls together. 
I guess the tip of thomas is not relevant for us as we really always use the same name now, so i guess we can easily migrate with a find and replace.
