### ISSUE TITLE
RFC: Avatar

### ISSUE THREAD

**Issue by mihajm** [goetzrobin/spartan#6]
# Avatar

## Assesment

| Time | Complexity | Risk | Description                                                                                          |
| ---- | ---------- | ---- | ---------------------------------------------------------------------------------------------------- |
| 2    | 2          | 1    | Unless I'm missing something, it's really just a bunch of styles & not much else with 0 dependencies |

## Dependencies

None

# brn

---

## API (proposed)

I think the shadcn/radix approach are good here, so I'd just use that. Only thing I'm not sure of is using components vs directives. I'm leaning towards directives, since they can provide some extra flexibility (img/picture use for AvatarImage & wouldn't require us managing default html attributes like alt/src etc.) but that's not really a big deal.

The fallback should be shown if no image template is provided or if the image is provided but emits an onError event.

```html
<!--Component approach-->

<brn-avatar>
  <brn-avatar-image src="..." alt="..." />
  <brn-avatar-fallback>JD</brn-avatar-fallback>
</brn-avatar>

<!--Directive approach-->

<brn-avatar>
  <img brnAvatarImage src="..." alt="..." />
  <span brnAvatarFallback>JD</span>
</brn-avatar>
```

Id also provide a few helpers for the fallback, like an initials pipe & an avatars component.

```typescript
const toInitial = (word: string): string => word[0].toLocaleUpperCase();

const firstAndLast = (words: string[], firstAndLastOnly = true) => firstAndLastOnly ? [words[0], words[words.length - 1]] : words;

// demo impl, needs a bit more work
@Pipe({
  name: 'initials'
  standalone: true
})
export class InitialsPipe implements PipeTransform {
  transform(name: string, firstAndLastOnly = true, delimiter = " "): string {
    return firstAndLast(name.split(delimiter), firstAndLastOnly).filter(Boolean).map(toInitial).join("").trim();
  }
}
```

The avatars component would simply be a container for multiple avatars & partially overlay them on top of each other.

```html
<!--This would display the max as a pure text component-->
<brn-avatars [max]="5">
  <brn-avatar *ngFor="let user of users">
    <img brnAvatarImage [src]="user.profileImg" [alt]="user.name + ' profile'" />
    <span brnAvatarFallback>{{user.name | initials}}</span>
  </brn-avatar>
  <span brnAvatarsMax>+{{users.length - 5}}</span>
</brn-avatars>

<!--or as an avatar-->
<brn-avatars [max]="5">
  <brn-avatar *ngFor="let user of users">
    <img brnAvatarImage [src]="user.profileImg" [alt]="user.name + ' profile'" />
    <span brnAvatarFallback>{{user.name | initials}}</span>
  </brn-avatar>
  <brn-avatar brnAvatarsMax>
    <span brnAvatarFallback>&plus;{{users.length - 5}}</span>
  </brn-avatar>
</brn-avatars>
```

### Proposed inputs (avatarFallback)

| Input     | Type             | Default   | Description                                                                       |
| --------- | ---------------- | --------- | --------------------------------------------------------------------------------- |
| autoColor | string/undefined | undefined | Auto-gens a background color & text-contrast color based on provided text content |

### Proposed inputs (avatars)

| Input | Type              | Default   | Description                                                                                          |
| ----- | ----------------- | --------- | ---------------------------------------------------------------------------------------------------- |
| max   | number/ undefined | undefined | The maximum number of avatars to display (if more they get displayed as the brnAvatarsMax component) |

# hlm

---

Not sure what hlm would do here, radix ui styles the component as much as I think is required, but if there are any styles you can think of, let me know. It can of course still just be re-exported as a hml component for api convenience.

# Aria

---

## Roles, States & Properties

Can't find much on aria rules for avatars, the image should have an alt tag of course, but that's about it & even that would be on the user if we go the directive route.

# Radix

---

## API

```typescript
import * as Avatar from "@radix-ui/react-avatar";

export default () => (
  <Avatar.Root>
    <Avatar.Image />
    <Avatar.Fallback />
  </Avatar.Root>
);
```

## Source

[https://www.radix-ui.com/docs/primitives/components/avatar](https://www.radix-ui.com/docs/primitives/components/avatar)

#shadcn

---

## API

```typescript
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

<Avatar>
  <AvatarImage src="https://github.com/shadcn.png" />
  <AvatarFallback>CN</AvatarFallback>
</Avatar>;
```

## Source

[https://ui.shadcn.com/docs/components/avatar](https://ui.shadcn.com/docs/components/avatar)

**Comment by goetzrobin** [comment]
Love it! I would argue that the delay and switching is the brn part and the hlm part is the styling of making the avatar round, etc. If you look at the radix CSS example you get a good idea of the separation of concerns

**Comment by benjaminforras** [comment]
For the _AvatarFallback_ I'd suggest to use structural directives like `*brnAvatarFallback` and inject it to the DOM whenever it's needed.

**Comment by mihajm** [comment]
Would make the impl. a bit prettier since we can just ngIf="canDisplayImage; else fallbackTemplate" it :) Are there any other benefits I'm not seeing?
