### ISSUE TITLE
Scroll Area width

### ISSUE THREAD

**Issue by jeremy-js-devweb** [goetzrobin/spartan#61]
### Please provide the environment you discovered this bug in.

There is an issue with `import {NgScrollbarModule} from 'ngx-scrollbar';`

### Which area/package is the issue in?

scroll-area

### Description

on my project I have exactly the same problem with the width.
The case is to switch between code and preview, the result is:

![image](https://github.com/goetzrobin/spartan/assets/131544192/38769834-b492-4d50-9902-15f809ffa24e)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
Might be solved in a similar fashion as this PR: https://github.com/goetzrobin/spartan/pull/51/files

**Comment by jeremy-js-devweb** [comment]
Indeed in my code with `<hlm-scroll-area class="h-[40rem] w-full rounded-md" [autoWidthDisabled]="true">` it works !

Maybe, it's better to set in the directive ?:
```ts
@Input()
  autoWidthDisabled = false;
```
