### ISSUE TITLE
User Class should not be set to Host too e.g. hlm-accordion-trigger

### ISSUE THREAD

**Issue by elite-benni** [goetzrobin/spartan#62]
### Please provide the environment you discovered this bug in.

spartan 0.0.1-alpha.313
"@angular/core": "17.0.2",

### Which area/package is the issue in?

accordion
sheet
dialog 
alert-dialog

### Description

Wenn setting a class on a   hlmAccordionTrigger the class is set to the button of the brn-accordion-trigger and to the brn-accordion-trigger.
![image](https://github.com/goetzrobin/spartan/assets/114084395/f0f695b6-0f4a-4a40-acca-0030c576949f)

### Please provide the exception or error you saw

```true
In this case the padding is added twice wich is not expected.
```

### Other information

My idea would be, that the class should not be set to the host (button) in this case. 
The userCls should not be set via setClassToCustomElement to the host. 

@goetzrobin if you also think would be better i would take a look on this. 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by homj** [comment]
This issue is tied to the use of `setClassToCustomElement`. It probably also affects `sheet`, `dialog` and `alert-dialog`

**Comment by elite-benni** [comment]
yes you are right. i will check all cases where the  `setClassToCustomElement` is used. 
Thanks homj for pointing that issue out in the first place! ;)

**Comment by elite-benni** [comment]
Actually i do not understand the `setClassToCustomElement` in the overlay components of `alert`, `sheet`and `dialog`
If i want to provide my customclasses for overlay, why should I use hlm anyway? ;) 

the only purpose is to set it to the `brn-dialog.component` via setOverlayClass which brn does.

This is an unresolvable problem, as the classes on the overlay componet are a completely different thing than settings the overlay classes in the `brn-dialog` . The user would expect to set the overlay classes, wich now happens, but also the classes are added to the overlay component. 

I would either just leave it as is, or delete the setClassToCustomElement completely from these two hlm Components. 
Maybe it is not even worth the time, making such a great deal out of that, because no one will ever use hlm with custom overlay classes. ;)
