### ISSUE TITLE
RFC: Aspect Ratio

### ISSUE THREAD

**Issue by goetzrobin** [goetzrobin/spartan#7]
# Avatar

## Assesment

| Time | Complexity | Risk | Description                                                                                          |
| ---- | ---------- | ---- | ---------------------------------------------------------------------------------------------------- |
| 2    | 2          | 1    | Just some CSS magic with absolute and relative positioning |

## Dependencies

None

# brn

---

## API (proposed)

shadcn simply reexports radix. Radix uses what I would say is the equivalent to Angular's content projection. I'd just use that.

```html
<brn-aspect-ratio [ratio]="3/4">
   <img alt="bla" src="bla"/>
</brn-aspect-ratio>
```

### Proposed inputs

| Input     | Type             | Default   | Description                                                                       |
| --------- | ---------------- | --------- | --------------------------------------------------------------------------------- |
| ratio | number | 1 | Aspect ratio of the projected content |

# hlm

---

Reexport brn.

# Aria

---

## Roles, States & Properties

DNA

# Radix

---

## API

```typescript
import React from 'react';
import * as AspectRatio from '@radix-ui/react-aspect-ratio';
import './styles.css';

const AspectRatioDemo = () => (
  <div className="Container">
    <AspectRatio.Root ratio={16 / 9}>
      <img
        className="Image"
        src="https://images.unsplash.com/photo-1535025183041-0991a977e25b?w=300&dpr=2&q=80"
        alt="Landscape photograph by Tobias Tullius"
      />
    </AspectRatio.Root>
  </div>
);

export default AspectRatioDemo;
```

## Source

https://www.radix-ui.com/docs/primitives/components/aspect-ratio

#shadcn

---

## API

```typescript
import Image from "next/image"
 
import { AspectRatio } from "@/components/ui/aspect-ratio"
 
export function AspectRatioDemo() {
  return (
    <AspectRatio ratio={16 / 9} className="bg-muted">
      <Image
        src="https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&dpr=2&q=80"
        alt="Photo by Drew Beamer"
        fill
        className="rounded-md object-cover"
      />
    </AspectRatio>
  )
}
```

## Source

```typescript
"use client"
 
import * as AspectRatioPrimitive from "@radix-ui/react-aspect-ratio"
 
const AspectRatio = AspectRatioPrimitive.Root
 
export { AspectRatio }
```
https://ui.shadcn.com/docs/components/aspect-ratio

**Comment by goetzrobin** [comment]
That's a good point! I'd almost say that would be something to mention in future docs. Prefer CSS and fallback to this component.


While I like the directive approach but we'd have to figure out how to wrap the children in the components we need. Content projection seems easier here. Since there will always be DOM nodes to needed to make it work I'd actually say component.

Would be cool to support a ratio in text form instead of a number. Maybe we can support the most common ones as text?

**Comment by mihajm** [comment]
Probably easier if its all text tbh as otherwise we need to parse out 16/9 out of 5.3333 since ng will just divide the numbers. We could use template literals to restrict it tho what we want. Otherwise were sort of forced into the position relative + absolute way of solving it.

```typescript
type Ratio = `${number}/${number`
```

Tho I also am up for aliasing a few common ones with declarative strings such as widescreen/phone etc.

I see what you mean with components, it sort of depends on impl here id say since all we need to do is add a single css property to the parent here. If we however wanted to do the relative/absolute approach a component would be easier.

**Comment by goetzrobin** [comment]
Since tailwind also supports aspect-ratio out of the box I say we stick with the positioning implementation. https://tailwindcss.com/docs/aspect-ratio

I do think the docs should state that there's a CSS property for that and it should be considered first.

**Comment by mihajm** [comment]
Great! Then numbers work and we just check if its 0 or less
