### ISSUE TITLE
Installation via Angular CLI does not provide latest brn and hlm components versions. 

### ISSUE THREAD

**Issue by jbruxelle** [goetzrobin/spartan#73]
### Please provide the environment you discovered this bug in.

Installed helm components and directives are not in the latest version (missing base component and content component for example for dialog or alertdialog) and brain dependencies are not in the latest version.

### Which area/package is the issue in?

dialog

### Description

Missing hlm-dialog.component.ts and hlm-dialog-content.component.ts at install. Same for alertdialog.
Does not match the documentation.

### Other information

P.S. : thank you for creating this. ❤️ 
Do not have time to contribute right now, but 300 have not been reached yet... 😄 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Just released the new versions! This should be fixed now!
