### ISSUE TITLE
Checkbox component can't find module '@spartan-ng/ui-icon-helm 

### ISSUE THREAD

**Issue by oidre** [goetzrobin/spartan#81]
### Please provide the environment you discovered this bug in.

Latest version 0.0.1-alpha.318

### Which area/package is the issue in?

checkbox

### Description

![checkbox](https://github.com/goetzrobin/spartan/assets/40825015/11d4b0f2-585d-41a7-959c-d6d215179563)
missing peerdependencies for checkbox component

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by elite-benni** [comment]
Didn't you get the prompt when adding checkbox, if you want to add icon primitive too?

**Comment by oidre** [comment]
> Didn't you get the prompt when adding checkbox, if you want to add icon primitive too?

No, i didn't get any prompt

maybe the issue can resolve with adding @spartan-ng/ui-icon-helm as peerdependences here?
![peerdep](https://github.com/goetzrobin/spartan/assets/40825015/f10a10d3-b3b3-4bbe-8e42-58b4767bdd50)

**Comment by elite-benni** [comment]
Ok, this is already fixed, I guess it is just not published yet. 

Sorry, I could have provided a workaround in the first place. 
You can add the icon with the same command as the other primitives 
`ng g @spartan-ng/cli:ui icon` for CLI 
`npx nx g @spartan-ng/cli:ui table` for nx

You can always run `ng g @spartan-ng/cli:ui` and choose the primitives you need.

**Comment by oidre** [comment]
> Ok, this is already fixed, I guess it is just not published yet.
> 
> Sorry, I could have provided a workaround in the first place. You can add the icon with the same command as the other primitives `ng g @spartan-ng/cli:ui icon` for CLI `npx nx g @spartan-ng/cli:ui icon` for nx
> 
> You can always run `ng g @spartan-ng/cli:ui` and choose the primitives you need.

i have installed the icon manually, but the primitive checkbox still appears
![terms](https://github.com/goetzrobin/spartan/assets/40825015/f6113c81-0cde-4842-89a6-c8a857d32211)

i think it's because NgStyle is not applied when the component published
![ngstyle](https://github.com/goetzrobin/spartan/assets/40825015/c78ae1a6-b899-441c-918a-9a29455f5e51)

**Comment by elite-benni** [comment]
Where do you see this ng Style? 

Acutally this this also an old bug, we planned to release the newest versions of the components soon. 
The old version of the brn-checkbox used sr-only by mistake, this was changed to ngStyle wich is probably not released by now. 
If you work with Tailwind, you can add the following to the tailwind.config.js
`safelist: ['sr-only'],`

Sorry for the confusion.

**Comment by goetzrobin** [comment]
New versions were just released @oidre! This should fix this issue! Please reopen if you still run into an issue
