### ISSUE TITLE
Components doesn't work in Brave browser

### ISSUE THREAD

**Issue by alexIslander** [goetzrobin/spartan#87]
### Please provide the environment you discovered this bug in.

Hi All,
i didn't find any specification a about browser support. I took a look around in the components section and [Accordion ](https://www.spartan.ng/components/accordion)failed to open in this Brave [Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (64-bit)](https://brave.com/latest/). 

In Opera work all fine. Opera One(version: 105.0.4970.21)

Cheers!

### Which area/package is the issue in?

accordion

### Description

Component doesn't open on click event

### Please provide the exception or error you saw

```true
ERROR TypeError: Cannot read properties of null (reading 'firstChild')
    at S9 (vendor-e35b74e6.js:7:96783)
    at I9 (vendor-e35b74e6.js:7:96992)
    at al (vendor-e35b74e6.js:7:96300)
    at K9 (vendor-e35b74e6.js:7:106763)
    at hi (vendor-e35b74e6.js:7:106097)
    at Hi (vendor-e35b74e6.js:7:106601)
    at template (accordion.page-bc7ee3e4.js:1:2488)
    at Uv (vendor-e35b74e6.js:7:63551)
    at $d (vendor-e35b74e6.js:7:82071)
    at kD (vendor-e35b74e6.js:7:81875)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by goetzrobin** [comment]
@elite-benni I think that's from our recent changes. We should probably add checks for this as we rely on a browser API directly

**Comment by elite-benni** [comment]
I will have a look at it.

**Comment by elite-benni** [comment]
I just downloaded the latest Version of Brave, which should be the same as you have.

`Version 1.61.109 Chromium: 120.0.6099.144 (Offizieller Build) (64-Bit)`

Cannot see any errors on click and it opens just as expected. 

Do you get the error on the docs site https://www.spartan.ng/components/accordion?

Is it possible that an extension is causing this error?

**Comment by alexIslander** [comment]
I can confirm that the issue was caused by a browser extension. 
Thank you for conducting the investigation!

**Comment by goetzrobin** [comment]
Closing this as this seems fixed! Thanks @elite-benni!
