### ISSUE TITLE
bug: select/option in dark mode is white text on white background

### ISSUE THREAD

**Issue by ajitzero** [goetzrobin/spartan#96]
### Please provide the environment you discovered this bug in.

The "Framework" dropdown in the first "Preview" tab in https://www.spartan.ng/components/card

Seen in Firefox & Microsoft Edge, on Windows 11.

### Which area/package is the issue in?

select

### Description

Using `[hlmInput]` on select turns the black text to white, but the background remains white.

A "proper" solution is to implement `select`, currently marked under "soon". There should be a simpler alternative CSS fix too, but then we would need to remember to add that for anywhere else we might add select/option later.

### Please provide the exception or error you saw

```true
_No response_
```

### Other information

Working in light mode:

![image](https://github.com/goetzrobin/spartan/assets/19947758/cba0c2c9-7d35-4bee-9313-8a9ce349637a)

![image](https://github.com/goetzrobin/spartan/assets/19947758/deda74db-5c53-4abc-98c8-c8323efb9297)

Not working in dark mode:

![On Microsoft Edge](https://github.com/goetzrobin/spartan/assets/19947758/21a18742-232f-4dde-a2e9-cf32f7cc7989)
![On Firefox](https://github.com/goetzrobin/spartan/assets/19947758/72e07f2f-5a0a-4300-b79a-3b51184c1993)

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by ajitzero** [comment]
This could be fixed with #70, not automatically, but we would need to use the newly introduced directive here.

**Comment by elite-benni** [comment]
#86 should fix this. 
but i would change it to #70 select when this is released.

**Comment by goetzrobin** [comment]
This is fixed by #86, which is now deployed to spartan.ng. Also if you are curious on how to fix this with only CSS this is the code that styles the native select on the spartan.ng page: https://github.com/goetzrobin/spartan/blob/da3f1819835d2de5bfa6388e05aeefd5e03971a4/apps/app/src/styles.css#L11
This issue might help also: https://github.com/chakra-ui/chakra-ui/issues/417
