### ISSUE TITLE
Notification component

### ISSUE THREAD

**Issue by jeremy-js-devweb** [goetzrobin/spartan#99]
### Which scope/s are relevant/related to the feature request?

Don't know / other

### Information

I have created a component with tailwind to display notification number:

```ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'code-up-notification',
  standalone: true,
  template: `
    <div
      class="absolute rounded-full -top-2 -end-2 inline-flex items-center justify-center w-6 h-6 text-[0.6rem] font-bold text-white bg-destructive">
      {{ _nbNotifications }}
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NotificationComponent {
  _nbNotifications = '';

  @Input({ required: true })
  set nbNotifications(nb: number) {
    this._nbNotifications = nb >= 99 ? '99+' : `${nb}`;
  }
}


```

Render:
![image](https://github.com/goetzrobin/spartan/assets/131544192/2b4b0f24-0210-4e77-88eb-f2b3a3689755)

It's just an idea for spartan.

and the parent:
```ts
<button
                hlmBtn
                class="relative"
                size="icon"
                variant="secondary">
                <hlm-icon size="sm" name="radixChatBubble" />
                <code-up-notification [nbNotifications]="98"/>
</button>
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by jeremy-js-devweb** [comment]
and in the parent component, you have just to add class='relative'

**Comment by benjaminforras** [comment]
It's awesome! However I think this component is out of scope for spartan-ui as it's main purpose is to provide components without styles and have the functionality ready. @goetzrobin can confirm.

**Comment by jeremy-js-devweb** [comment]
> It's awesome! However I think this component is out of scope for spartan-ui as it's main purpose is to provide components without styles and have the functionality ready. Maybe @goetzrobin can confirm.

Yes, I think you have right.

**Comment by goetzrobin** [comment]
I agree. However, I do like the idea of having some "community-driven" components. Maybe we can include it in an example that we build similar to one of those here: https://ui.shadcn.com/examples/mail
